spring:
  datasource:
    url: jdbc:h2:mem:socialdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: warn
security:
  jwt:
    secret: ${JWT_SECRET:change-me-please-change-me-32chars-min}
    ttl-min: 60
cloud:
  aws:
    region: eu-central-1          # pick your region
    s3:
      bucket: your-bucket-name    # replace with an existing bucket
